// import mongoose from "mongoose";
// const uniqueValidator = require("mongoose-unique-validator");

const mongoose = require("mongoose");

const playerSchema = new mongoose.Schema({
  ID: { type: Number, required: [true], unique: true },
  Name: { type: String, required: [true] },
  FullName: { type: String, required: [true] },
  Age: { type: Number, required: [true] },
  Height: { type: Number },
  Weight: { type: Number },
  PhotoUrl: { type: String },
  Nationality: { type: String },
  Overall: { type: Number },
  Potential: { type: Number },
  Growth: { type: Number },
  TotalStats: { type: Number },
  BaseStats: { type: Number },
  Positions: { type: String },
  BestPosition: { type: String },
  Club: { type: String },
  ValueEUR: { type: Number },
  WageEUR: { type: Number },
  ReleaseClause: { type: Number },
  ClubPosition: { type: String },
  contractUntil: { type: Number },
  ClubNumber: { type: Number },
  ClubJoined: { type: Number },
  OnLoad: { type: Boolean },
  NationalTeam: { type: String },
  NationalPosition: { type: String },
  NationalNumber: { type: Number },
  PreferredFoot: { type: String },
  IntReputation: { type: Number },
  WeakFoot: { type: Number },
  SkillMoves: { type: Number },
  AttackingWorkRate: { type: String },
  DeffensiveWorkRate: { type: String },
  PaceTotal: { type: Number },
  ShootingTotal: { type: Number },
  PassingTotal: { type: Number },
  DribblingTotal: { type: Number },
  DefendingTotal: { type: Number },
  PhysicalityTotal: { type: Number },
  Crossing: { type: Number },
  Finishing: { type: Number },
  HeadingAccuracy: { type: Number },
  ShortPassing: { type: Number },
  Volleys: { type: Number },
  Dribbling: { type: Number },
  Curve: { type: Number },
  FKAccuracy: { type: Number },
  LongPassing: { type: Number },
  BallControl: { type: Number },
  Acceleration: { type: Number },
  SprintSpeed: { type: Number },
  Agility: { type: Number },
  Reactions: { type: Number },
  Balance: { type: Number },
  ShotPower: { type: Number },
  Jumping: { type: Number },
  Stamina: { type: Number },
  Strength: { type: Number },
  LongShots: { type: Number },
  Aggression: { type: Number },
  Interceptions: { type: Number },
  Positioning: { type: Number },
  Vision: { type: Number },
  Penalties: { type: Number },
  Composure: { type: Number },
  Marking: { type: Number },
  StandingTackle: { type: Number },
  SlidingTackle: { type: Number },
  GKDiving: { type: Number },
  GKHandling: { type: Number },
  GKKicking: { type: Number },
  GKPositioning: { type: Number },
  GKReflexes: { type: Number },
  STRating: { type: Number },
  LWRating: { type: Number },
  CFRating: { type: Number },
  RFRating: { type: Number },
  RWRating: { type: Number },
  CAMRating: { type: Number },
  LMRating: { type: Number },
  CMRating: { type: Number },
  RMRating: { type: Number },
  LWBRating: { type: Number },
  CDMRating: { type: Number },
  RWBRating: { type: Number },
  LBRating: { type: Number },
  CBRating: { type: Number },
  RBRating: { type: Number },
  GKRating: { type: Number },
});

// playerSchema.plugin(uniqueValidator, {
//   message: "Error, player already exists."
// })
// mongoose.models = {};

// var Player = mongoose.model("Player", playerSchema);

// export default Player;

module.exports =
  mongoose.models.Player || mongoose.model("Player", playerSchema);
